[project]
name = "mlb-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.3",
    "pybaseball>=2.2.7",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
